.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vhkd_qt test_vhkd_qt
clean: FORCE
	$(MAKE) -C .. vhkd_qt_clean test_vhkd_qt_clean
check: FORCE
	$(MAKE) -C .. test_vhkd_qt_check
vhkd-qt vhkd-qt.exe: FORCE
	 $(MAKE) -C .. vhkd_qt
